In [4]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix


predictions = np.load('out/prediction_result.npy')
true_labels = np.load('out/test_labels.npy')


predicted_labels = np.argmax(predictions, axis=1)
true_labels = np.argmax(true_labels, axis=1)

accuracy = accuracy_score(true_labels, predicted_labels)
conf_matrix = confusion_matrix(true_labels, predicted_labels)

print(f'Accuracy: {accuracy * 100:.2f}%')
print('Confusion Matrix:')
print(conf_matrix)

np.savetxt('out/confusion_matrix.txt', conf_matrix, fmt='%d')


Accuracy: 93.77%
Confusion Matrix:
[[300  19   1   0]
 [  8 215   1   0]
 [  5   5  81   0]
 [  1   0   0   6]]
